<?php
/**
 * 基于商品类实现CD类
 * User: Xuefeng Luo
 * Date: 2020/3/14
 * Time: 12:07 PM
 */

namespace Patteron;


class CdProduct extends ShopProduct
{
    // CD 长度
    private $palylength = 0;

    public function __construct($title, $firstName, $mainName, $price, $playLength)
    {
        // 扩展父类构造函数
        parent::__construct($title, $firstName, $mainName, $price);
        $this->palylength = $playLength;
    }

    /**
     * 获取播放时长
     * @return int
     */
    public function getPlayLength()
    {
        return $this->palylength;
    }

    /**
     * 重写汇总信息
     * 实现CD需要暂时的汇总信息
     * @return string
     */
    public function getSummaryLine()
    {
        $base = parent::getSummaryLine(); // TODO: Change the autogenerated stub
        $base .= "：playing time - {$this->palylength}";
        return $base;
    }


}