<?php
/**
 * Created by PhpStorm.
 * User: zerone
 * Date: 2020/3/31
 * Time: 8:47 PM
 */

namespace DesignPatterns\Structural\Proxy;


class RecordProxy extends Record
{
    private $isDirty = false;

    private $isInitialized = false;

    public function __construct(array $data = [])
    {
        parent::__construct($data);

        if (count($data) > 0) {
            $this->isInitialized = true;
            $this->isDirty = true;
        }
    }

    public function __set($name, $value)
    {
        $this->isDirty = true;
        parent::__set($name, $value); // TODO: Change the autogenerated stub


    }

    public function isDirty()
    {
        return $this->isDirty;
    }

}